stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  script:
    - npm install eslint --save-dev
    - eslint .

test:
  stage: test
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - npm install -g heroku
    - heroku login -i
    - git push heroku master
